version : '3'

services:
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootrootroot'
      MYSQL_USER: 'python'
      MYSQL_PASSWORD: 'password'
    volumes: 
      - ./backend/db/mysql:/docker-entrypoint-initdb.d/
      - ./backend/db/mysql/host_address.cnf:/etc/mysql/host_address.cnf
    networks:
      net1:
        ipv4_address: 172.20.0.9
    ports:
      - 3306:3306
  api:
    image: python:3
    volumes:
      - ./backend/py:/usr/src/app
    networks:
      net1:
        ipv4_address: 172.20.0.10
    ports:
      - 5000:5000
    command: 
      - /bin/sh
      - -c
      - |
        cd /usr/src/app
        pip install --no-cache-dir -r requirements.txt
        python3 main.py
  #       uvicorn main:app --host 0.0.0.0 --port 8000
  proxy:
    image: nginxinc/nginx-unprivileged:latest
    volumes:
      - ./backend/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/rn/thd_app1/dist:/usr/share/nginx/html/static
    restart: always
    networks:
        net1:
          ipv4_address: 172.20.0.11
    ports:
      - 80:80   
networks:
  net1:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"